config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :categories
  get 'sessions/new'

  get 'robs/index'

  post 'robs/new'
  # resources :robs
  #post 'destroy/index'
  #post 'robs/new'
  get 'comments/new/rob_id/:rob_id' => 'comments#new'
   post "/comments/edit/rob_id/:rob_id'"  => 'comments#edit'
  resources :comments
  
  resources :feeds, only: [:show, :edit, :update, :destroy]
  resources :robs, only: [:new, :create, :edit, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :comments, only: [:new, :create, :edit, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  
  resources :robs do
    resources :comments
  end
  
  resources :robs do
    resources :news
  end
  resources :robs do
    resources :categories
  end
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  root to: 'sessions#new'
  
  
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
   resources :robs do
    collection do
      post :confirm
    end
   end
#  devise_scope :user do
 #  get "register", :to => "devise/registrations#new"
  # get "login", :to => "devise/sessions#new"
   #get "logout", :to => "devise/sessions#destroy"
  #end
   #devise_for :installs
end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/rob.rb
class Rob < ApplicationRecord
     validates :content, length: { in: 1..1000 }
    validates :title, presence: true
    validates :image, presence: true
      #validates :category, presence: true
    belongs_to :user
    belongs_to :category
    # belongs_to :comment
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    # def self.search(search)
    # where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%") 
    # end
    def self.search(term)
    if term
    where('title LIKE ?', "%#{term}%")
    else
    all
    end
    end
     
end

app/controllers/robs_controller.rb
class RobsController < ApplicationController
  before_action :set_rob, only: [:show, :edit, :update, :destroy] 
  #before_action :Force_login
  #before_action :authenticate_user!
  #skip_before_action :verify_authenticity_token
 
  
  def index
    @robs = Rob.all
    @search = Rob.search(params[:q])
    # @robs = @search.result
    @favorite = Favorite.all
    @comment = Comment.all
    @category = Category.all
    
    # if params[:search]
    # @robs = Rob.search(params[:search]).order("created_at DESC")
    # else
    # @robs = Rob.all.order("created_at DESC")
    # end
     @robs = Rob.search(params[:term])
     @robs = if params[:term]
    Rob.where('Title LIKE ?', "%#{params[:term]}%")
  else
    Rob.all
  end
  end

  # Add
  
  
  def new
   @category ||= Category.all
   if params[:back]
      @rob = Rob.new(rob_params)
    else
     @rob = Rob.new    
   end
  # @robs = Rob.new
  # @robs.user_id = current_user.id
  end
  
  def create
    @rob = Rob.new(rob_params)
    
    @rob.image.retrieve_from_cache! params[:cache][:image] 
    # @rob.user_id = current_user.id
    respond_to do |format|
    if @rob.save
      # Switch to the list screen and display a message saying "You have created new blog!"
     # RobMailer.rob_mail(@rob).deliver
      #redirect_to robs_path, Notice: "You have created new rob!"
       format.html { redirect_to @rob, notice: 'News is successfully created.' }
      format.js { render :index }
    else
      # Redraw the input form.
     format.html { render :new }
      format.js { render :index }
    end
  end
  end
   def confirm
    @category ||= Category.all
    @rob = Rob.new(rob_params)
     render :new if @rob.invalid?
   end
  
  def show
    # 追記する
     @robs = Rob.find(params[:id])
     @favorite = current_user.favorites.find_by(rob_id: @robs.id)
      @comment = @rob.comments.build
  @comments = @rob.comments
  
 # @category = @rob.category.build
 # @categories = @rob.categories
     
  end
  def edit
     @robs = Rob.find(params[:id])
  end
    
   def update
    @robs = Rob.find(params[:id])
    if @robs.update(rob_params)
      redirect_to robs_path, Notice: "You have edited Your Account！"
    else
      render 'edit'
    end
   end
  
  def destroy
    @rob.destroy
    redirect_to robs_path, Notice: "You Have Deleted This News!"
  end
  
  
 
  #Omitted
  private
  #Before_action : Set_rob, only: [:show, :edit, :update, :destroy] 
   def rob_params
    params.require(:rob).permit(:title, :content, :image,:category_id).merge(user: current_user)
   end
  
  def set_rob
    @rob = Rob.find(params[:id])
  end
  #def destroy
   # @robs.destroy
    #redirect_to robs_path, Notice: "You have deleted the rob!"
#  end
  
  
  #Omission
  
  #Omission
  #Omitted

end  

app/helpers/robs_helper.rb
module RobsHelper
def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_robs_path
    elsif action_name == 'edit'
      rob_path
    end
  end
end

app/views/robs/_form.html.erb
<%= form_with(model: @rob, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @rob.errors.any? %>
    <div id="error_explanation">
      <h2><%= @rob.errors.count %>errors occurred.</h2>
      <ul>

      <% @rob.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="rob_category" style="width:400px;margin-left: 411px;">
  
    <%= form.select(:category_id,style:'width: 400px;') do %>
        <% @category.each do |l| %>
          <%= content_tag(:option, l.name, value: l.id) %>
        <% end %>
    <% end %>
  </div>
  

  <div class="rob_title">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control' %>
  </div>
  <div class="rob_title">
    <%= form.label :content %>
    <%= form.text_field :content, class:'form-control' %>
  </div>
  <div class="rob_title">
    <%= form.label :image %>
    <%= form.file_field :image, id: :rob_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  
  <%= form.submit %>
<% end %>



<%= link_to "Return to List of News screen", robs_path %>

app/views/robs/_index.html.erb
<%= form_with(model: [rob, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<!-- This description will be the comment input form displayed in the rob's show screen -->

app/views/robs/confirm.html.erb
<!DOCTYPE html>
<html>
<body>
  <div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">> 
     
    <div class="table-responsive">


      
<h2>Comfirm</h2>

<%= form_with(model: @rob, url: robs_path, local: true) do |form| %>
     <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :category_id %>
  <p>Title:<%= @rob.title %></p>
  <p>Body:<%= @rob.content %></p>
   <p>Body:<%= image_tag(@rob.image.url(:thumb)) %></p>
   <%= hidden_field_tag :"cache[image]",@rob.image.cache_name%>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @rob, url: new_rob_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <%= form.submit "Back", name: 'back' %>
<% end %>



    </div>
     </div>
</body>
</html>

app/views/robs/edit.html.erb
 <!DOCTYPE html>
<html>
<body>
 
  <div class="row">
 <div class="col-sm-4" style="background-color:lightgray;">
       

<%= form_with(model: @robs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image, id: :feed_image %>
  <%= form.hidden_field :image_cache %>
</div>
  <h2>Edit Contents</h2>

  
  <%= form.submit %>
<% end %>

</div></div>
</body>
</html>

app/views/robs/index.js.erb
$("#robs_area").html("<%= j(render 'robs/index', { robs: @rob.rob.robs, rob: @rob.rob }) %>")
$("textarea").val('')

app/views/robs/new.html.erb
 <!DOCTYPE html>
<html>
<body>
 

    <div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">> 

<h2>Tell Us News</h2>


  <%= render 'form' %>

 
    </div></div>
  
</body>
</html>    
    

app/views/robs/show.html.erb
<!DOCTYPE html>
<html>
<body>

 <div class="row">
   <div class="col-sm-12" style="background-color:lavender;">
   
  
       <h2>Contents Details </h2>
           
<% unless @robs.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Cancel favorites', favorite_path(@robs.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'To favorite', favorites_path(rob_id: @robs.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<p id="notice"><%= notice %></p>
  <div class="blog-text">
    <p><strong>Title</strong></p>
    <p><%= @rob.title %></p>
    <p><strong>Content</strong></p>
    <p><%= @rob.content %></p>
  </div>
  <p>
  
  <strong>Image:</strong>
  <%= image_tag @robs.image_url, style:'width:250px;height:250px;' %>
  
</p>
  
  <div id="comments_area">
  <!-- render for displaying posted comments list in a blog detail page -->
    <%= render partial: 'comments/index', locals: { comments: @comments, rob: @rob } %>
  </div>

  <!-- render for displaying comment entering field in a blog detail page -->
  <%= render partial: 'comments/form', locals: { comment: @comment, rob: @rob } %>

  

<%= link_to 'Edit', edit_rob_path(@rob) %> |
  <%= link_to 'Return', robs_path %>
  
  
</div>
</div>
</body>
</html>    
    