config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :categories
  get 'sessions/new'

  get 'robs/index'

  post 'robs/new'
  # resources :robs
  #post 'destroy/index'
  #post 'robs/new'
  get 'comments/new/rob_id/:rob_id' => 'comments#new'
   post "/comments/edit/rob_id/:rob_id'"  => 'comments#edit'
  resources :comments
  
  resources :feeds, only: [:show, :edit, :update, :destroy]
  resources :robs, only: [:new, :create, :edit, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :comments, only: [:new, :create, :edit, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  
  resources :robs do
    resources :comments
  end
  
  resources :robs do
    resources :news
  end
  resources :robs do
    resources :categories
  end
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  root to: 'sessions#new'
  
  
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
   resources :robs do
    collection do
      post :confirm
    end
   end
#  devise_scope :user do
 #  get "register", :to => "devise/registrations#new"
  # get "login", :to => "devise/sessions#new"
   #get "logout", :to => "devise/sessions#destroy"
  #end
   #devise_for :installs
end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, length: { maximum: 255 },
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                #attr_accessor :password, :password_confirmation 
                 before_save { email.downcase! }
                
 validates :password, length: { minimum: 6 }
 has_secure_password
   validates :image, presence: true
  #belongs_to :company
  has_many :favorites, dependent: :destroy
  has_many :favorite_robs, through: :favorites, source: :rob
  has_many :robs,    dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :categories, dependent: :destroy
  
  mount_uploader :image, ImageUploader
   # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 #
  #field :encrypted_password, :type => String, :default => ""
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!, :except => [:show, :index]
 def index
    @user = User.all
     @search = User.search(params[:q])
     @user = @search.result
    @category = Category.all
 end
 def new
    @user = User.new
      @category ||= Category.all
     
 end
 
 def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
 end
 def show
    @user = User.find(params[:id])
    
    @robs = @user.favorite_robs 
 end
 def edit
     @user = User.find(params[:id])
 end
 def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path, Notice: "You have edited Your Account！"
      else
        render 'edit'
      end
 end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.hrml.erb
<%= hidden_field_tag :"cache[image]",@picture.image.cache_name %>
<%= image_tag(@picture.image.url) %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<body>
   
     <div class="row">
 <div class="col-sm-8" style="background-color:lightgray;">
 

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name, class:'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class:'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class:'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class:'form-control' %>
  <div class="image">
  <%= f.label :image %>
  <%= f.file_field :image, id: :robs_image %>
  <%= f.hidden_field :image_cache %>
</div>

  <%= f.submit "Edit my account", class:'btn btn-primary' %>
<% end %>

 
    </div> </div></div>
   
</body>
</html>    
    

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<body>
    <div id="page-wrap">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My Page</a>
    </div>
    
    </div>
    
    
</nav>

<div class="container">
    
   
    <article>
        <div class="contents">
            <ul class="row">
    <li class="col-md-offset-1 col-md-6">contents1</li>
    <li class="col-md-offset-2 col-md-6">contents2</li>
    
</ul>
        </div>
        
    </article>
    
</div>

</table>
<footer> <p> Copyright © 2018</p>
<h>Contact Us</h>
<p>Email: nzeroberto@gmail.com</p>
<p>Phone: +250787104291</p>
</footer>  
</div>
</div>
</body>
</html>    
    

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<body>
  
<div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name, class:'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class:'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class:'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class:'form-control' %>
<div class="image">
  <%= f.label :image %>
  <%= f.file_field :image, id: :robs_image %>
  <%= f.hidden_field :image_cache %>
</div>
  <%= f.submit "Create my account", class:'btn btn-primary' %>
<% end %>


    </div></div>
   
</body>
</html>    
    

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<body>
   
 <div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
 <% user = current_user %>
  
   <%= link_to "Edit My Account", edit_user_path %>
   <%= link_to 'Post News', new_rob_path%>
     <%= link_to 'News Category', new_category_path%>

    
<h1><%= @user.name %>'s page</h1>

<p>email address: <%= @user.email %></p>

</div>
   <div class="col-sm-12" style="background-color:lavenderblush;">
<h1>Most Favorited News</h1>
<div class="table-responsive">
<table class="table">
<tr>
<th class="col-md-4">Windows</th> 
<th class="col-md-4">Mac</th> 
<th class="col-md-4">Linux</th> 
<th class="col-md-4">Android</th> 
<th class="col-md-4">Iphone</th> 
<th class="col-md-4">Hardware</th> 
<th class="col-md-4">Software</th> 
<th class="col-md-4">Title</th> 
<th class="col-md-4">Content</th> 
<th class="col-md-4">Image</th> 
</tr>
<% @robs.each do |rob| %>
<tr>
<td><%= rob.windows %> </td>
<td><%= rob.mac %> </td>
<td><%= rob.linux %> </td>
<td><%= rob.android %> </td>
<td><%= rob.iphone %> </td>
<td><%= rob.hardware %> </td>
<td><%= rob.software %> </td>
<td><%= rob.title %> </td>

<td><%= rob.content %> </td>
<!--<td><%= rob.image %> </td>-->

<td><div class="profile"><%= image_tag(rob.image_url, style:'width:80px;height:80px;')%></div></td>
</tr>

<% end %>
</table>
</div>
  </div>
    
</body>
</html>    
    

    