config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :categories
  get 'sessions/new'

  get 'robs/index'

  post 'robs/new'
  # resources :robs
  #post 'destroy/index'
  #post 'robs/new'
  get 'comments/new/rob_id/:rob_id' => 'comments#new'
   post "/comments/edit/rob_id/:rob_id'"  => 'comments#edit'
  resources :comments
  
  resources :feeds, only: [:show, :edit, :update, :destroy]
  resources :robs, only: [:new, :create, :edit, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :comments, only: [:new, :create, :edit, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  
  resources :robs do
    resources :comments
  end
  
  resources :robs do
    resources :news
  end
  resources :robs do
    resources :categories
  end
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  root to: 'sessions#new'
  
  
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
   resources :robs do
    collection do
      post :confirm
    end
   end
#  devise_scope :user do
 #  get "register", :to => "devise/registrations#new"
  # get "login", :to => "devise/sessions#new"
   #get "logout", :to => "devise/sessions#destroy"
  #end
   #devise_for :installs
end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/category.rb
class Category < ApplicationRecord
  
    validates :name,  presence: true, length: { maximum: 300 }
    has_many :robs
    belongs_to :user
    
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :user_is_logged_in, only: [:new,:edit,:show,:index]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @user = User.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
     @category = Category.find(params[:id])
     @news=@category.robs
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    # @rob = Rob.find(params[:rob_id])
    @category = Category.new(category_params)
    @user =User.find_by(id: session[:user_id])
    @category.user_id=@user.id
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'This Category is successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
 
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :category_name, class:'form-control' %>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<html>
<body>
 
<div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

</div></div>

</body>
</html>  

app/views/categories/index.html.erb
<div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
<p id="notice"><%= notice %></p>


<h1>Categories</h1>

<% for category in @categories do %>
    <%= link_to category.name, category %>
<% end %>

<%= link_to 'New Category', new_category_path %>
</div></div>

app/views/categories/new.html.erb
<html>
<body>
 
<div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', users_path %>
</div></div>

</body>
</html>    
    

app/views/categories/show.html.erb
<html>
<body>
 
<div class="row">
 <div class="col-sm-12" style="background-color:lightgray;">
  
<p id="notice"><%= notice %></p>
 News for <%= @category.name %>
<p>
  <strong>Name:</strong>
  
  <% @news.each do |new|%>
    <%=image_tag(new.image_url, style:'width:250px;height:250px;')%><br>
    <%=new.title%><br>
    <%=new.content%><br>
  <% end %>
 
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', robs_path %>

</div>
</div>
</body>
</html>  