config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :categories
  get 'sessions/new'

  get 'robs/index'

  post 'robs/new'
  # resources :robs
  #post 'destroy/index'
  #post 'robs/new'
  get 'comments/new/rob_id/:rob_id' => 'comments#new'
   post "/comments/edit/rob_id/:rob_id'"  => 'comments#edit'
  resources :comments
  
  resources :feeds, only: [:show, :edit, :update, :destroy]
  resources :robs, only: [:new, :create, :edit, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :comments, only: [:new, :create, :edit, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  
  resources :robs do
    resources :comments
  end
  
  resources :robs do
    resources :news
  end
  resources :robs do
    resources :categories
  end
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  root to: 'sessions#new'
  
  
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
   resources :robs do
    collection do
      post :confirm
    end
   end
#  devise_scope :user do
 #  get "register", :to => "devise/registrations#new"
  # get "login", :to => "devise/sessions#new"
   #get "logout", :to => "devise/sessions#destroy"
  #end
   #devise_for :installs
end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
    validates :name,  presence: true, length: { maximum: 300 }
    has_many :robs
    belongs_to :user
    
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :rob
  belongs_to :user
  # validates :name, presence: true
  validates :content, presence: true
   
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :rob
end

app/models/rob.rb
class Rob < ApplicationRecord
     validates :content, length: { in: 1..1000 }
    validates :title, presence: true
    validates :image, presence: true
      #validates :category, presence: true
    belongs_to :user
    belongs_to :category
    # belongs_to :comment
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    # def self.search(search)
    # where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%") 
    # end
    def self.search(term)
    if term
    where('title LIKE ?', "%#{term}%")
    else
    all
    end
    end
     
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, length: { maximum: 255 },
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                #attr_accessor :password, :password_confirmation 
                 before_save { email.downcase! }
                
 validates :password, length: { minimum: 6 }
 has_secure_password
   validates :image, presence: true
  #belongs_to :company
  has_many :favorites, dependent: :destroy
  has_many :favorite_robs, through: :favorites, source: :rob
  has_many :robs,    dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :categories, dependent: :destroy
  
  mount_uploader :image, ImageUploader
   # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 #
  #field :encrypted_password, :type => String, :default => ""
  
end

app/controllers/robs_controller.rb
class RobsController < ApplicationController
  before_action :set_rob, only: [:show, :edit, :update, :destroy] 
  #before_action :Force_login
  #before_action :authenticate_user!
  #skip_before_action :verify_authenticity_token
 
  
  def index
    @robs = Rob.all
    @search = Rob.search(params[:q])
    # @robs = @search.result
    @favorite = Favorite.all
    @comment = Comment.all
    @category = Category.all
    
    # if params[:search]
    # @robs = Rob.search(params[:search]).order("created_at DESC")
    # else
    # @robs = Rob.all.order("created_at DESC")
    # end
     @robs = Rob.search(params[:term])
     @robs = if params[:term]
    Rob.where('Title LIKE ?', "%#{params[:term]}%")
  else
    Rob.all
  end
  end

  # Add
  
  
  def new
   @category ||= Category.all
   if params[:back]
      @rob = Rob.new(rob_params)
    else
     @rob = Rob.new    
   end
  # @robs = Rob.new
  # @robs.user_id = current_user.id
  end
  
  def create
    @rob = Rob.new(rob_params)
    
    @rob.image.retrieve_from_cache! params[:cache][:image] 
    # @rob.user_id = current_user.id
    respond_to do |format|
    if @rob.save
      # Switch to the list screen and display a message saying "You have created new blog!"
     # RobMailer.rob_mail(@rob).deliver
      #redirect_to robs_path, Notice: "You have created new rob!"
       format.html { redirect_to @rob, notice: 'News is successfully created.' }
      format.js { render :index }
    else
      # Redraw the input form.
     format.html { render :new }
      format.js { render :index }
    end
  end
  end
   def confirm
    @category ||= Category.all
    @rob = Rob.new(rob_params)
     render :new if @rob.invalid?
   end
  
  def show
    # 追記する
     @robs = Rob.find(params[:id])
     @favorite = current_user.favorites.find_by(rob_id: @robs.id)
      @comment = @rob.comments.build
  @comments = @rob.comments
  
 # @category = @rob.category.build
 # @categories = @rob.categories
     
  end
  def edit
     @robs = Rob.find(params[:id])
  end
    
   def update
    @robs = Rob.find(params[:id])
    if @robs.update(rob_params)
      redirect_to robs_path, Notice: "You have edited Your Account！"
    else
      render 'edit'
    end
   end
  
  def destroy
    @rob.destroy
    redirect_to robs_path, Notice: "You Have Deleted This News!"
  end
  
  
 
  #Omitted
  private
  #Before_action : Set_rob, only: [:show, :edit, :update, :destroy] 
   def rob_params
    params.require(:rob).permit(:title, :content, :image,:category_id).merge(user: current_user)
   end
  
  def set_rob
    @rob = Rob.find(params[:id])
  end
  #def destroy
   # @robs.destroy
    #redirect_to robs_path, Notice: "You have deleted the rob!"
#  end
  
  
  #Omission
  
  #Omission
  #Omitted

end  

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
def devise_mapping
  Devise.mappings[:user]
end

def resource_name
  devise_mapping.name
end

def resource_class
  devise_mapping.to
end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/robs_helper.rb
module RobsHelper
def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_robs_path
    elsif action_name == 'edit'
      rob_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def user_is_logged_in
    if current_user.nil?
        redirect_to sessions_new_path
    end
 end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <title>ICT</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 

  <%= csrf_meta_tags %>

   <body>
   
     <nav class="navbar navbar-toggleable-md navbar-expand-md navbar-light bg-light">
      <div class="container">
           <%=link_to image_tag("logo.png", width:'100px',height:'50px'), root_path,class:'navbar-brand'%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           
          </li>
       
        </ul>
        <ul class="navbar-nav">
        
          
         <% if logged_in? %>  
          
            <li><a href=""><%= link_to "My Account Detail", user_path(current_user.id) %></a></li>
            <li><a href=""><%= link_to " Home", robs_path %></li>
            <li><a href=""><%= link_to "Logout", session_path(current_user.id), method: :delete %></a></li>
            
             
             
           <li> <a><%= image_tag current_user.image.url , class:'img-circle' %>
           
            
           <%= form_tag(robs_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
         </a></li><br>
             
<% end %>
    
         <% else %>
            <li><a href=""><%= link_to "Sign up", new_user_path %></a></li>
            <li><a href=""><%= link_to "Login", new_session_path %></a></li>
         <% end %>
         
          <li>
        </ul>
       <style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
   
}

li {
    float: left;
}

li a {
    display: block;
     color: #00008b;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change the link color to #111 (black) on hover */
/*li a:hover {*/
/*    background-color: #111;*/
/*}   */



</style>
      </div>
    </div>
</nav>
<div class="contain">
 
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">WHO WE ARE</a></li>
    <li><a data-toggle="tab" href="#menu1">WHAT WE DO</a></li>
    <li><a data-toggle="tab" href="#menu2">TERMS AND CONDITIONS</a></li>
    <li><a data-toggle="tab" href="#menu3">CONTACT US</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
     
      <p1> A private Technology website news firm.</p1>
    </div>
    <div id="menu1" class="tab-pane fade">
      
      <p1> Teach people Technology and trends </p1>
    </div>
    <div id="menu2" class="tab-pane fade">
      
      <p1>Do not make other uncomfortable with your comments.</p1>
    </div>
    <div id="menu3" class="tab-pane fade">
      
      <p1> Look At the footer for Contact Details</p1>
    </div>
    <style>
      p1{font-family: monospace;
      font-size:1.5rem;
      font-style: oblique;
      color: #fffacd;
      /* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
}
    </style>
  </div>
</div>

  
   <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <p class="notice"><%= notice %></p>
       <p  class="alert"><%= alert %></p>
      <% end %>
      
  
       <%= yield %>
<div class="row">
 <div class="col-sm-4" style="background-color:lightgray;"></div></div>
   <div class="row">
	 <div class="col-sm-4" style="background-color:lavender;"></div>
	   <div class="col-sm-14" style="background-color:lavenderblush;"></div></div>
  
     
<style>

/*footer {*/
/*     position: absolute;*/
   
/*    bottom: 0;*/
/*    width: 100%;*/
/*      min-height: 60px;*/
/*    background-color:#2c3e50;*/
/*    color: white;*/
/*    text-align: center;*/
/*    padding-top: 24px;*/
    
/*    }*/
footer
{ width: 100%;
  font-family: 'trebuchet ms', sans-serif;
  font-size: 100%;
  height: 300px;
  /*padding: 28px 0 5px 0;*/
  text-align: center; 
  background: #3B3939 url(footer.png) repeat-x;
  color: #A8AA94;}

footer p
{ line-height: 1.7em;
  padding: 0 0 10px 0;}

footer a
{ color: #A8AA94;
  text-decoration: none;}

footer a:hover
{ color: #FFF;
  text-decoration: none;}

table {margin-bottom:200px;
  
}
li{
  padding-bottom:80px;
}
article { 
    display: block;
}

</style>
 
 <footer class="footer"><p> Copyright © 2018</p>
<h>Contact Us</h>
<p>Email: nzeroberto@gmail.com</p>
<p>Phone: +250787104291</p>

 <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">HTML5 Web Templates</a></p>
    
</footer>


</body>
 
</html>